#!/bin/sh

HOMEDIR="/Users/dou"
DIRS="
Data
Projects
Labs
Downloads
"

for dir in $DIRS; do
    rm -f /root/$dir && ln -s $HOMEDIR/$dir /root/$dir
    su - docker -c "rm -f /home/docker/$dir && ln -s $HOMEDIR/$dir /home/docker/$dir"
done

echo "
127.0.0.1 default localhost localhost.local

# The following lines are desirable for IPv6 capable hosts
# (added automatically by netbase upgrade)

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

192.168.3.2  r.dev
192.168.3.11 r.book

" > /etc/hosts
