#!/bin/sh

HOMEDIR="/Users/dou"
DIRS="
Data
Projects
Labs
Downloads
"

for dir in $DIRS; do
    rm -f /root/$dir && ln -s $HOMEDIR/$dir /root/$dir
    su - docker -c "rm -f /home/docker/$dir && ln -s $HOMEDIR/$dir /home/docker/$dir"
done
